#!/bin/bash

set -e

echo "Installing dependencies"
npm install
cd web && npm install && cd -
cd web/frontend && npm install && cd -

echo "Trying to install Rust"
if [ -f "rust-toolchain" ] || [ -f "rust-toolchain.toml" ]; then
    echo "rust-toolchain configuration found, skipping default installation"
else
    rustup toolchain install 1.66.1
    rustup override set 1.66.1
fi

cargo install cargo-wasi
